# Header
logo_text: Home
menu:
  About Me: about
  Archives: archives
  Categories: categories
  Tags: tags
  RSS: /atom.xml

# Content
excerpt_link: Read Moreâ€¦
toc: false #  Whether to show the table of contents in articles
fancybox: true

# Miscellaneous
google_analytics: UA-4869398-4
favicon: /favicon.png

# Share
share_jia: false
share_addthis: false

# RSS
rss: /atom.xml